# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\VADIM\Python\SFedU\third_term\knowledge_representation\lab_2\ui\dictionary_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dictionary_window(object):
    def setupUi(self, dictionary_window):
        dictionary_window.setObjectName("dictionary_window")
        dictionary_window.resize(800, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dictionary_window.sizePolicy().hasHeightForWidth())
        dictionary_window.setSizePolicy(sizePolicy)
        dictionary_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        dictionary_window.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(dictionary_window)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(dictionary_window)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_lp = QtWidgets.QWidget()
        self.tab_lp.setObjectName("tab_lp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_lp)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.list_lp = QtWidgets.QListWidget(self.tab_lp)
        self.list_lp.setMinimumSize(QtCore.QSize(0, 0))
        self.list_lp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_lp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_lp.setObjectName("list_lp")
        self.verticalLayout_2.addWidget(self.list_lp)
        self.tabWidget.addTab(self.tab_lp, "")
        self.tab_pp = QtWidgets.QWidget()
        self.tab_pp.setObjectName("tab_pp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_pp)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.list_pp = QtWidgets.QListWidget(self.tab_pp)
        self.list_pp.setMinimumSize(QtCore.QSize(0, 0))
        self.list_pp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_pp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_pp.setObjectName("list_pp")
        self.verticalLayout_3.addWidget(self.list_pp)
        self.tabWidget.addTab(self.tab_pp, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_open = QtWidgets.QPushButton(dictionary_window)
        self.button_open.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_open.setFont(font)
        self.button_open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_open.setIconSize(QtCore.QSize(24, 24))
        self.button_open.setObjectName("button_open")
        self.horizontalLayout.addWidget(self.button_open)
        self.button_delete = QtWidgets.QPushButton(dictionary_window)
        self.button_delete.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_delete.setFont(font)
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_delete.setIconSize(QtCore.QSize(24, 24))
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.button_exit = QtWidgets.QPushButton(dictionary_window)
        self.button_exit.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_exit.setFont(font)
        self.button_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_exit.setIconSize(QtCore.QSize(24, 24))
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout.addWidget(self.button_exit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dictionary_window)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(dictionary_window)

    def retranslateUi(self, dictionary_window):
        _translate = QtCore.QCoreApplication.translate
        dictionary_window.setWindowTitle(_translate("dictionary_window", "Словарь"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lp), _translate("dictionary_window", "Лингвистические переменные"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pp), _translate("dictionary_window", "Продукционные правила"))
        self.button_open.setText(_translate("dictionary_window", "Открыть"))
        self.button_delete.setText(_translate("dictionary_window", "Удалить"))
        self.button_exit.setText(_translate("dictionary_window", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dictionary_window = QtWidgets.QWidget()
    ui = Ui_dictionary_window()
    ui.setupUi(dictionary_window)
    dictionary_window.show()
    sys.exit(app.exec_())
